make-pot: add `subtract-and-merge` flag
wp-cli/i18n-command pull request #267
Opened 2021-07-12 20:40 UTC by swissspidy

This PR adds a new `--subtract-and-merge` flag to the `make-pot` command, which can be used in combination with `--subtract`. When used, source code references from the generated POT file will instead be added to the POT file(s) passed to `--subtract`

Example:

```bash
# In foo-plugin/
wp i18n make-pot . foo-plugin.pot --subtract=exceptions.pot

# foo-plugin.pot will not contain any of the strings that are also in exceptions.pot
# exceptions.pot will now however contain all source code references for these strings
```

While I suggested adding dedicated commands for this feature a few years ago, in hindsight thats seems a bit overkill. It's quite the advanced configuration option that's probably only ever used for WordPress core, so just adding a flag feels like the better choice here.

Fixes #105

2021-07-13 14:35 UTC, swissspidy commented
@ocean90 Would this solve the issue for dotorg?

2021-07-13 16:05 UTC, ocean90 commented
> @ocean90 Would this solve the issue for dotorg?

As of https://meta.trac.wordpress.org/changeset/10063/ this is actually no issue anymore. My approach is also preserving any comments by using the `mergeWith()` method. Maybe this should be considered here as well?

2021-07-13 16:32 UTC, swissspidy commented
Good suggestion with `mergeWith()` 👍 

Are there chances that you would adopt this new `--subtract-and-merge` flag should it be add? If not, we might not want to bother implementing it.

2021-07-14 06:34 UTC, ocean90 commented
If if works the same as the current implementation, sure why not. Less code I have to maintain. 😅

2021-07-20 10:57 UTC, swissspidy commented
It should work the same way now and is ready for review.

2021-07-20 14:16 UTC, ocean90 requested changes

2021-07-20 14:16 UTC, ocean90 commented on src/MakePotCommand.php
> +	 * : Whether source code references from the generated POT file should be instead added to the POT file
```suggestion
	 * : Whether source code references and comments from the generated POT file should be instead added to the POT file
```

2021-07-20 21:24 UTC, schlessera approved these changes

2021-07-20 21:24 UTC, merged