Combine theme.json and block.json extractor classes
wp-cli/i18n-command pull request #319
Opened 2022-05-02 13:38 UTC by swissspidy

Fixes #287

2022-05-02 13:39 UTC, swissspidy commented
cc @gziolo

2022-05-02 14:55 UTC, swissspidy commented
Looks like the existing theme i18n schema parser does not support  cases like 

```json
  "keywords": [ "block keyword" ],
```

as seen in `block.json`

So that needs some fiddling to enable support and make the tests pass

2022-05-02 21:13 UTC, swissspidy commented
@schlessera I'm running into some fatal errors here on PHP < 7.4. Perhaps you have some ideas here? Not sure which one of my changes could have caused that...

2022-05-03 07:05 UTC, schlessera commented
@swissspidy The problem was the use of `private` access in the `IterableCodeExtractor` trait. That worked fine until you extended a class that was using that trait.

2022-05-03 08:01 UTC, swissspidy commented
Ah 💡 🤦  Thanks!

2022-05-04 12:21 UTC, gziolo commented
I think it's a good idea to use the file from `wordpress-develop` for now. I'm still not sure whether using the canonical URL similar to https://schemas.wp.org/trunk/block.json as discussed in the parent issue would work so nicely as it can be ahead of WordPress core.

Anyway, it looks like this PR has everything covered. Nice work, thank you for bringing i18n schemas up to date ❤️

2022-07-04 15:59 UTC, schlessera requested changes

2022-07-04 15:59 UTC, schlessera commented on src/JsonSchemaExtractor.php
> +			|| 300 <= $response->status_code
```suggestion
			|| 300 <= (int) $response->status_code
```

2022-07-04 15:59 UTC, schlessera commented on src/JsonSchemaExtractor.php
> +			WP_CLI::debug( "Failed to download from URL $url", 'make-pot' );
```suggestion
			WP_CLI::debug( "Failed to download from URL {$url}", 'make-pot' );
```

2022-07-04 15:59 UTC, schlessera commented on src/JsonSchemaExtractor.php
> +		WP_CLI::debug( "Parsing file $file", 'make-pot' );
```suggestion
		WP_CLI::debug( "Parsing file {$file}", 'make-pot' );
```

2022-07-04 15:59 UTC, schlessera commented on src/JsonSchemaExtractor.php
> +	/**
```suggestion
	/**
	 * Load the i18n from a remote URL or fall back to a local schema in case of an error.
```

2022-07-04 15:59 UTC, schlessera commented on src/JsonSchemaExtractor.php
> +	protected static $schema_cache = [];
```suggestion
	/**
	 * Static cache for the remote schema files.
	 *
	 * @var array<string, string>
	 */
	protected static $schema_cache = [];
```

2022-07-04 16:08 UTC, schlessera approved these changes

2022-07-04 16:24 UTC, merged